void updateKernel() {
    uint gid = gl_GlobalInvocationID.x;
    if (gid == 0) {
        if (resetValuesOrDecrementDeadBodies==1u) {
            //Reset Queues
            headIn=0u;
            tailIn = 0u;
            mergeQueueTail = 0u;
            mergeQueueHead = 0u;
        }
        else {
            //Update Number of Bodies
            sim.numBodies -= sim.justDied;
            sim.justDied = 0u;

    }
        }
}
